server:
  port: 6815

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/index_demo
    username: ${crypto.user}
    password: ${crypto.passwd}

common:
  user:
    username: pycro
    password: ${crypto.passwd}
    address: Suzhou
    email: pycro6815@163.com
  hostname: centos
  defaultFtp:
    host: 172.16.0.1
    ip: 23306
    user: root
    password: BDsec2022,,

crypto:
  user: root
  passwd: 12345678