server:
  port: 6815

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/index_demo
    username: ${crypto.user}
    password: ${crypto.passwd}
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
common:
  user:
    username: pycro
    password: ${crypto.passwd}
    address: Suzhou
    email: pycro6815@163.com
  hostname: centos
  defaultFtp:
    host: 172.16.0.1
    ip: 23306
    user: root
    password: BDsec2022,,

crypto:
  user: root
  passwd: 12345678